#!/usr/bin/env python3
"""
Register a font file the console should serve from disk, without committing it.

Why this exists: a font installed into Windows is not necessarily visible to a
browser, because browsers enumerate system fonts once at process start. Serving
the file over localhost makes it render immediately, in any browser, with no
restart.

It also keeps licensing clean. `hud/fonts-local/` is gitignored, so a font that
may be used but not redistributed (PUSAB, or anything you have licensed
personally) renders on your machine and never lands in the public repo. On a
fresh clone the folder is absent, the stylesheet 404s harmlessly, and the CSS
stack falls through to the vendored open-licensed fallback.

Usage:
    python scripts/add-local-font.py "C:\\path\\to\\PUSAB___.TTF"
    python scripts/add-local-font.py PUSAB___.TTF --family Pusab
    python scripts/add-local-font.py --list
"""

from __future__ import annotations

import argparse
import shutil
import struct
import sys
from pathlib import Path

LOCAL = Path(__file__).resolve().parent.parent / "hud" / "fonts-local"

FORMATS = {".ttf": "truetype", ".otf": "opentype",
           ".woff2": "woff2", ".woff": "woff"}


def family_of(path: Path) -> str | None:
    """Read the family name out of a TTF/OTF `name` table."""
    try:
        d = path.read_bytes()
        num = struct.unpack(">H", d[4:6])[0]
        off, name_off = 12, None
        for _ in range(num):
            tag, _c, o, _l = struct.unpack(">4sIII", d[off:off + 16])
            off += 16
            if tag == b"name":
                name_off = o
        if name_off is None:
            return None
        _fmt, count, stroff = struct.unpack(">HHH", d[name_off:name_off + 6])
        # Collect every family record, then prefer the Windows one. Taking the
        # first match and guessing the encoding from platform id alone decodes a
        # UTF-16 string as latin-1 and yields "P u s a b", which then matches
        # nothing in CSS.
        found: dict[int, str] = {}
        for i in range(count):
            pid, _eid, _lid, nid, ln, o = struct.unpack(
                ">HHHHHH", d[name_off + 6 + i * 12: name_off + 6 + i * 12 + 12])
            if nid != 1:
                continue
            raw = d[name_off + stroff + o: name_off + stroff + o + ln]
            for enc in ("utf-16-be", "latin-1"):
                try:
                    s = raw.decode(enc)
                except Exception:
                    continue
                # a latin-1 read of UTF-16 leaves interleaved NULs
                s = s.replace("\x00", "").strip()
                if s:
                    found.setdefault(pid, s)
                    break
        return found.get(3) or found.get(1) or next(iter(found.values()), None)
    except Exception:
        return None
    return None


def rebuild_css() -> int:
    faces = []
    for f in sorted(LOCAL.iterdir()):
        if f.name == "local.css" or f.suffix.lower() not in FORMATS:
            continue
        fam = family_of(f) or f.stem
        faces.append(
            "@font-face {\n"
            f"  font-family: '{fam}';\n"
            "  font-style: normal;\n"
            "  font-weight: 400;\n"
            "  font-display: swap;\n"
            f"  src: url(/fonts-local/{f.name}) format('{FORMATS[f.suffix.lower()]}');\n"
            "}\n")
        print(f"    {fam:<24} {f.name}  ({f.stat().st_size // 1024} KB)")
    header = ("/* Generated by scripts/add-local-font.py. Do not commit this\n"
              "   folder: it holds fonts that may be used but not redistributed. */\n\n")
    (LOCAL / "local.css").write_text(header + "\n".join(faces), encoding="utf-8")
    return len(faces)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("font", nargs="?", help="path to a .ttf/.otf/.woff2 file")
    ap.add_argument("--family", help="override the family name")
    ap.add_argument("--list", action="store_true", help="show what is registered")
    args = ap.parse_args()

    LOCAL.mkdir(parents=True, exist_ok=True)

    if args.list or not args.font:
        print(f"\n  local fonts in {LOCAL}:")
        n = rebuild_css()
        print(f"\n  {n} face(s) registered in hud/fonts-local/local.css\n")
        return 0

    src = Path(args.font)
    if not src.is_file():
        print(f"  no such file: {src}", file=sys.stderr)
        return 1
    if src.suffix.lower() not in FORMATS:
        print(f"  unsupported type {src.suffix}; expected one of "
              f"{', '.join(sorted(FORMATS))}", file=sys.stderr)
        return 1

    dest = LOCAL / src.name
    shutil.copy2(src, dest)
    fam = args.family or family_of(dest) or dest.stem
    print(f"\n  added {src.name} as '{fam}'")
    rebuild_css()
    print(f"\n  Reload the console. Nothing here is committed.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
